
name: Build, Test, and Deploy

on:
  push:
    branches:
      - main  # Adjust this to match your default branch if it's not 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this as per your project's requirements

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()  # Ensures deployment runs only if build and test are successful and on the main branch
    steps:
    - uses: actions/checkout@v2

    - name: Heroku Deploy
      uses: akhileshns/heroku-deploy@v3.12.12  # This is a community action for Heroku deployment
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: your-email@example.com  # Replace with your Heroku account email
